# Arquivo: .streamlit/secrets.toml
# ATENÇÃO: Nunca compartilhe este arquivo com ninguém!

[winthor]
usuario = "NUTRICAO"
senha = "nutr1125mmf"
ip = "192.168.222.20"       # Coloque o IP real do servidor
porta = "1521"           # Geralmente é 1521
servico = "WINT"         # Nome do serviço do banco (SID/Service Name)

